services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=counselAI
      - POSTGRES_USER=counsel_user
      - POSTGRES_DB=counsel_db

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "hsinpa@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "counselAI"
    ports:
      - "5040:80"