services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=counselAI
      - POSTGRES_USER=counsel_user
      - POSTGRES_DB=counsel_db
