services:
  db:
    image: pgvector/pgvector:pg16
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=counselAI
      - POSTGRES_USER=counsel_user
      - POSTGRES_DB=counsel_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5040:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: hsinpa@gmail.com
      PGADMIN_DEFAULT_PASSWORD: counselAI
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: